# 1) Series
pd.Seires() 함수를 사용하여 정의, <-- python리스트,numpy array 등이 함수의 인자로 입력

In [1]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.dtype

dtype('int64')

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj.shape

(4,)

In [8]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','c','a'])
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [9]:
# Series는 dictionary 와 같이 사용 가능
sdata = {
    'charles': 35000,
    'hyunsu': 35000,
    'hayoung': 35000,
    'joohee': 35000
}

In [11]:
obj3 = pd.Series(sdata)
obj3

charles    35000
hyunsu     35000
hayoung    35000
joohee     35000
dtype: int64

In [12]:
obj3.name = 'Salary'
obj3.index.name = 'name'
obj3

name
charles    35000
hyunsu     35000
hayoung    35000
joohee     35000
Name: Salary, dtype: int64

In [13]:
obj3.index=['A','B','C','D']
obj3

A    35000
B    35000
C    35000
D    35000
Name: Salary, dtype: int64

# 2) DataFrame
pd.DataFrame() 함수를 사용해서 정의. 파이썬의 딕셔너리, numpy array, list등 데이터 프레임으로 활용 가능

In [14]:
data = {"names" : ["aa","aa","aa","bb","bb"],
        "years" : [2014,2015,2016,2017,2018],
        "points" : [1.5,1.7,3.6,2.4,2.9]}

df = pd.DataFrame(data)
df

  names  years  points
0    aa   2014     1.5
1    aa   2015     1.7
2    aa   2016     3.6
3    bb   2017     2.4
4    bb   2018     2.9

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
df.columns

Index(['names', 'years', 'points'], dtype='object')

In [17]:
df.values

array([['aa', 2014, 1.5],
       ['aa', 2015, 1.7],
       ['aa', 2016, 3.6],
       ['bb', 2017, 2.4],
       ['bb', 2018, 2.9]], dtype=object)

In [ ]:
df.describe()       # 계산이 가능한 컬럼에 한해서 각 컬럼의 평균,분산,최소/최대값 등 기본 통계량을
                    # 산출한 결과를 보여줌... 데이터를 읽어온 후, 데이터 셋을 전체적으로 살펴보고자
                    # 할때 사용하기 유용함

             years    points
count     5.000000  5.000000
mean   2016.000000  2.420000
std       1.581139  0.864292
min    2014.000000  1.500000
25%    2015.000000  1.700000
50%    2016.000000  2.400000
75%    2017.000000  2.900000
max    2018.000000  3.600000

In [21]:
df2 = pd.DataFrame(data, columns=["years","names","points","penalty"],
                   index = ["one","two","three","four","five"],
                   )
df2

       years names  points penalty
one     2014    aa     1.5     NaN
two     2015    aa     1.7     NaN
three   2016    aa     3.6     NaN
four    2017    bb     2.4     NaN
five    2018    bb     2.9     NaN

In [22]:
df2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [23]:
df2.columns

Index(['years', 'names', 'points', 'penalty'], dtype='object')

In [24]:
df2.values

array([[2014, 'aa', 1.5, nan],
       [2015, 'aa', 1.7, nan],
       [2016, 'aa', 3.6, nan],
       [2017, 'bb', 2.4, nan],
       [2018, 'bb', 2.9, nan]], dtype=object)

In [26]:
df2.describe()

             years    points
count     5.000000  5.000000
mean   2016.000000  2.420000
std       1.581139  0.864292
min    2014.000000  1.500000
25%    2015.000000  1.700000
50%    2016.000000  2.400000
75%    2017.000000  2.900000
max    2018.000000  3.600000

In [27]:
df3 = pd.DataFrame(data, columns=["names"])
df3

  names
0    aa
1    aa
2    aa
3    bb
4    bb