In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'name' : ["aa","aa","aa","bb","bb"],
        'year' : [2014, 2015, 2016, 2017, 2018],
        'point' : [1.5, 1.7, 3.6, 2.4, 2.9]}

df = pd.DataFrame(data, columns=['year','name','point','penalty'],
                  index=['one', 'two', 'three', 'four', 'five'])

df

       year name  point penalty
one    2014   aa    1.5     NaN
two    2015   aa    1.7     NaN
three  2016   aa    3.6     NaN
four   2017   bb    2.4     NaN
five   2018   bb    2.9     NaN

In [3]:
# year 열만 얻기
df['year']

one      2014
two      2015
three    2016
four     2017
five     2018
Name: year, dtype: int64

In [4]:
df.year

one      2014
two      2015
three    2016
four     2017
five     2018
Name: year, dtype: int64

In [6]:
# 2개 이상의 열을 얻기
df[['year', 'point']]

       year  point
one    2014    1.5
two    2015    1.7
three  2016    3.6
four   2017    2.4
five   2018    2.9

In [7]:
df.penalty = 0.5
df

       year name  point  penalty
one    2014   aa    1.5      0.5
two    2015   aa    1.7      0.5
three  2016   aa    3.6      0.5
four   2017   bb    2.4      0.5
five   2018   bb    2.9      0.5

In [ ]:
# 행마다 다른 값 넣기
df['penalty'] = [0.1, 0.2, 0.3, 0.4, 0.5]
df

       year name  point  penalty
one    2014   aa    1.5      0.1
two    2015   aa    1.7      0.2
three  2016   aa    3.6      0.3
four   2017   bb    2.4      0.4
five   2018   bb    2.9      0.5

In [12]:
# column 추가하고 값 넣기
df['zeros'] = np.arange(5)
df

       year name  point  penalty  zeros
one    2014   aa    1.5      0.1      0
two    2015   aa    1.7      0.2      1
three  2016   aa    3.6      0.3      2
four   2017   bb    2.4      0.4      3
five   2018   bb    2.9      0.5      4

In [13]:
val = pd.Series([-1.2, -1.5, -1.7], index = ["two", "four", "five"])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [ ]:
# 'debt' 열 추가 및 val Series 데이터를 debt 안에 넣기, 인덱스 같은 것끼리 답 대입(자동)
df['debt'] = val
df

       year name  point  penalty  zeros  debt
one    2014   aa    1.5      0.1      0   NaN
two    2015   aa    1.7      0.2      1  -1.2
three  2016   aa    3.6      0.3      2   NaN
four   2017   bb    2.4      0.4      3  -1.5
five   2018   bb    2.9      0.5      4  -1.7

In [15]:
df['net_points'] = df['point'] - df['penalty']

In [16]:
df['hight_points'] = df['net_points'] > 2.0

In [17]:
df

       year name  point  penalty  zeros  debt  net_points  hight_points
one    2014   aa    1.5      0.1      0   NaN         1.4         False
two    2015   aa    1.7      0.2      1  -1.2         1.5         False
three  2016   aa    3.6      0.3      2   NaN         3.3          True
four   2017   bb    2.4      0.4      3  -1.5         2.0         False
five   2018   bb    2.9      0.5      4  -1.7         2.4          True

In [18]:
del df['hight_points']
del df['net_points']
del df['zeros']

In [19]:
df

       year name  point  penalty  debt
one    2014   aa    1.5      0.1   NaN
two    2015   aa    1.7      0.2  -1.2
three  2016   aa    3.6      0.3   NaN
four   2017   bb    2.4      0.4  -1.5
five   2018   bb    2.9      0.5  -1.7

In [20]:
df.columns

Index(['year', 'name', 'point', 'penalty', 'debt'], dtype='object')

In [22]:
df.index.name = "Order"
df.columns.name = "Info"
df

Info   year name  point  penalty  debt
Order
one    2014   aa    1.5      0.1   NaN
two    2015   aa    1.7      0.2  -1.2
three  2016   aa    3.6      0.3   NaN
four   2017   bb    2.4      0.4  -1.5
five   2018   bb    2.9      0.5  -1.7

In [23]:
# 행 제어하기
df[0:3]

Info   year name  point  penalty  debt
Order
one    2014   aa    1.5      0.1   NaN
two    2015   aa    1.7      0.2  -1.2
three  2016   aa    3.6      0.3   NaN

In [24]:
# 범위 인덱싱 제어하기
df['two':'four']

Info   year name  point  penalty  debt
Order
two    2015   aa    1.7      0.2  -1.2
three  2016   aa    3.6      0.3   NaN
four   2017   bb    2.4      0.4  -1.5

In [25]:
# 행선택하는 권장 방법 --> .Loc(), .iloc()

# .Loc() 행 / 열 명칭으로 검색
df.loc['two']       # 인덱스 'two' 행의 전체 값 가져오기

Info
year       2015
name         aa
point       1.7
penalty     0.2
debt       -1.2
Name: two, dtype: object

In [27]:
df.loc['two' : "four"]

Info   year name  point  penalty  debt
Order
two    2015   aa    1.7      0.2  -1.2
three  2016   aa    3.6      0.3   NaN
four   2017   bb    2.4      0.4  -1.5

In [29]:
# columns 'points' 의 특정 값 가져오기
df.loc['two' : 'four', 'point']

Order
two      1.7
three    3.6
four     2.4
Name: point, dtype: float64

In [30]:
df.loc[:, 'year']

Order
one      2014
two      2015
three    2016
four     2017
five     2018
Name: year, dtype: int64

In [31]:
df['year'].name = 'year'

In [32]:
df.loc[:, 'year']

Order
one      2014
two      2015
three    2016
four     2017
five     2018
Name: year, dtype: int64

In [34]:
# 두개 이상의 열 검색
df.loc[:, ['year', 'name']]

Info   year name
Order
one    2014   aa
two    2015   aa
three  2016   aa
four   2017   bb
five   2018   bb

In [35]:
# 범위 인덱싱
df.loc['two' : 'four', ['year', 'name']]

Info   year name
Order
two    2015   aa
three  2016   aa
four   2017   bb

In [36]:
# 행 추가
df.loc['six', :] = [2019, 'cc', 3.3, 0.6, -1.3]

In [37]:
df

Info     year name  point  penalty  debt
Order
one    2014.0   aa    1.5      0.1   NaN
two    2015.0   aa    1.7      0.2  -1.2
three  2016.0   aa    3.6      0.3   NaN
four   2017.0   bb    2.4      0.4  -1.5
five   2018.0   bb    2.9      0.5  -1.7
six    2019.0   cc    3.3      0.6  -1.3

In [42]:
df.loc['seven', :] = [2020, 'dd', 1.0, 0.3, None]

In [43]:
df

Info     year name  point  penalty  debt
Order
one    2014.0   aa    1.5      0.1   NaN
two    2015.0   aa    1.7      0.2  -1.2
three  2016.0   aa    3.6      0.3   NaN
four   2017.0   bb    2.4      0.4  -1.5
five   2018.0   bb    2.9      0.5  -1.7
six    2019.0   cc    3.3      0.6  -1.3
seven  2020.0   dd    1.0      0.3   NaN

In [44]:
# .lioc() numpy 방식으로(행 / 열 자리값으로) 행 가져올때 사용
df.iloc[3]

Info
year       2017.0
name           bb
point         2.4
penalty       0.4
debt         -1.5
Name: four, dtype: object

In [58]:
df.iloc[3, 3]

np.float64(0.4)

In [55]:
df.iloc[0:3, 0:3]

Info     year name  point
Order
one    2014.0   aa    1.5
two    2015.0   aa    1.7
three  2016.0   aa    3.6

In [59]:
# 행과 열의 범위를 별도 지정해서 검색ㄷ
df.iloc[[0,1,3], [1,2]]

Info  name  point
Order
one     aa    1.5
two     aa    1.7
four    bb    2.4

In [60]:
df.iloc[:, 1:4]

Info  name  point  penalty
Order
one     aa    1.5      0.1
two     aa    1.7      0.2
three   aa    3.6      0.3
four    bb    2.4      0.4
five    bb    2.9      0.5
six     cc    3.3      0.6
seven   dd    1.0      0.3

In [63]:
# 값 하나만 가져오기
df.iloc[-1, 1]

'dd'

# 불리언 인덱싱

In [64]:
df

Info     year name  point  penalty  debt
Order
one    2014.0   aa    1.5      0.1   NaN
two    2015.0   aa    1.7      0.2  -1.2
three  2016.0   aa    3.6      0.3   NaN
four   2017.0   bb    2.4      0.4  -1.5
five   2018.0   bb    2.9      0.5  -1.7
six    2019.0   cc    3.3      0.6  -1.3
seven  2020.0   dd    1.0      0.3   NaN

In [66]:
# year의 2014년도보다 큰 값 찾기

df['year'] > 2014

Order
one      False
two       True
three     True
four      True
five      True
six       True
seven     True
Name: year, dtype: bool

In [69]:
df.loc[:, 'year'] > 2014

Order
one      False
two       True
three     True
four      True
five      True
six       True
seven     True
Name: year, dtype: bool

In [71]:
add = df['year'] > 2014
df['add'] = add
df.loc[:]

Info     year name  point  penalty  debt    add
Order
one    2014.0   aa    1.5      0.1   NaN  False
two    2015.0   aa    1.7      0.2  -1.2   True
three  2016.0   aa    3.6      0.3   NaN   True
four   2017.0   bb    2.4      0.4  -1.5   True
five   2018.0   bb    2.9      0.5  -1.7   True
six    2019.0   cc    3.3      0.6  -1.3   True
seven  2020.0   dd    1.0      0.3   NaN   True

In [72]:
df.loc[df['year'] > 2014, :]

Info     year name  point  penalty  debt   add
Order
two    2015.0   aa    1.7      0.2  -1.2  True
three  2016.0   aa    3.6      0.3   NaN  True
four   2017.0   bb    2.4      0.4  -1.5  True
five   2018.0   bb    2.9      0.5  -1.7  True
six    2019.0   cc    3.3      0.6  -1.3  True
seven  2020.0   dd    1.0      0.3   NaN  True

In [79]:
df.loc[df['name'] == 'bb', ['name', 'point']]

Info  name  point
Order
four    bb    2.4
five    bb    2.9

In [81]:
df.loc[(df['point'] > 2) & (df['point'] < 3), :]

Info     year name  point  penalty  debt   add
Order
four   2017.0   bb    2.4      0.4  -1.5  True
five   2018.0   bb    2.9      0.5  -1.7  True

In [90]:
# 새로운 값 대입
df.loc[df['point'] > 3, 'penalty'] = 0

In [91]:
df

Info     year name  point  penalty  debt    add
Order
one    2014.0   aa    1.5      0.1   NaN  False
two    2015.0   aa    1.7      0.2  -1.2   True
three  2016.0   aa    3.6      0.0   NaN   True
four   2017.0   bb    2.4      0.4  -1.5   True
five   2018.0   bb    2.9      0.5  -1.7   True
six    2019.0   cc    3.3      0.0  -1.3   True
seven  2020.0   dd    1.0      0.3   NaN   True

In [92]:
df.loc[df['name'] == 'bb', ['name', 'point']]

Info  name  point
Order
four    bb    2.4
five    bb    2.9

In [ ]:
# Subject.scv 파일을 읽어 와서 'df' 변수에 저장하기
data = pd.read_csv("../12/Subjects.csv", encoding="utf-8")
df2 = pd.DataFrame(data)
df2

    class name  kor  eng  math  science
0       1  aaa   67   87    90       98
1       1  bbb   45   45    56       98
2       1  ccc   95   59    96       88
3       1  ddd   65   94    89       98
4       1  eee   45   65    78       98
5       1  fff   78   76    98       89
6       2  ggg   87   67    65       56
7       2  hhh   89   98    78       78
8       2  iii  100   78    56       65
9       2  jjj   99   89    87       87
10      2  kkk   98   45    56       54
11      2  lll   65   89    87       78

In [113]:
# df DataFrame 에 '총점' 과 '평균' 열을 추가하여 각 학생 별 총점, 평균 점수를 입력
df2.loc[:, 'total']  = None
df2.loc[:, 'avg'] = None
df2
# 행 삭제
# df.drop(index=['total', 'avg'], inplace=True)
# df

    class name  kor  eng  math  science total   avg
0       1  aaa   67   87    90       98  None  None
1       1  bbb   45   45    56       98  None  None
2       1  ccc   95   59    96       88  None  None
3       1  ddd   65   94    89       98  None  None
4       1  eee   45   65    78       98  None  None
5       1  fff   78   76    98       89  None  None
6       2  ggg   87   67    65       56  None  None
7       2  hhh   89   98    78       78  None  None
8       2  iii  100   78    56       65  None  None
9       2  jjj   99   89    87       87  None  None
10      2  kkk   98   45    56       54  None  None
11      2  lll   65   89    87       78  None  None

In [119]:
for i in df2.index:
  total = np.sum(df2.loc[i, ['kor', 'eng', 'math', 'science']])
  avg = round(total / 4, 2)
  df2.loc[df2.index[i], ['total', 'avg']] = [total, avg]

df2

    class name  kor  eng  math  science total    avg
0       1  aaa   67   87    90       98   342   85.5
1       1  bbb   45   45    56       98   244   61.0
2       1  ccc   95   59    96       88   338   84.5
3       1  ddd   65   94    89       98   346   86.5
4       1  eee   45   65    78       98   286   71.5
5       1  fff   78   76    98       89   341  85.25
6       2  ggg   87   67    65       56   275  68.75
7       2  hhh   89   98    78       78   343  85.75
8       2  iii  100   78    56       65   299  74.75
9       2  jjj   99   89    87       87   362   90.5
10      2  kkk   98   45    56       54   253  63.25
11      2  lll   65   89    87       78   319  79.75

In [122]:
# class 1과 class 2 의 평균 점수를 각각 출력
class1 = df2.loc[df2['class'] == 1, :]
class2 = df2.loc[df2['class'] == 2, :]
class1
class2

    class name  kor  eng  math  science total    avg
6       2  ggg   87   67    65       56   275  68.75
7       2  hhh   89   98    78       78   343  85.75
8       2  iii  100   78    56       65   299  74.75
9       2  jjj   99   89    87       87   362   90.5
10      2  kkk   98   45    56       54   253  63.25
11      2  lll   65   89    87       78   319  79.75

In [125]:
if np.mean(class1.loc[:, 'avg']) > np.mean(class2.loc[:, 'avg']):
  print(f"1반이 짱 : {np.mean(class1.loc[:, 'avg'])}")
else:
  print(f"2반이 짱 : {np.mean(class2.loc[:, 'avg'])}")

1반이 짱 : 79.04166666666667